src/expressions/sql.pegjs
src/external/druidExternal.ts
test/overall/sqlParser.mocha.coffee

DESCRIBE query support

---

CHANGELOG.md
compile-tsc
dev-docs/new-action-checklist.md
docs/expressions.md
docs/plyql.md
src/actions/timeRangeAction.ts
src/expressions/baseExpression.ts
src/expressions/plyql.pegjs
test/actions/actions.mocha.coffee
test/overall/compute.mocha.coffee
test/overall/expressionParser.mocha.coffee
test/overall/plyqlParser.mocha.coffee
test/overall/stringification.mocha.coffee

timeRangeAction

---

CHANGELOG.md
src/actions/andAction.ts
src/actions/matchAction.ts
test/functional/druidFunctional.mocha.coffee
test/overall/compute.mocha.coffee

Fixes: https://github.com/implydata/plyql/issues/5

AND simplify bug fix

---

.idea/inspectionProfiles/Project_Default.xml
src/expressions/baseExpression.ts
src/external/druidExternal.ts
test/external/druidExternal.mocha.js
test/functional/crossFunctional.mocha.js

Allow `.apply('wiki', '$wiki.filter($isAnonymous)')`

filter on ref

---

CHANGELOG.md
data/druid/Dockerfile
data/druid/init
src/actions/concatAction.ts
src/actions/extractAction.ts
src/actions/overlapAction.ts
src/external/druidExternal.ts
test/external/druidExternal.mocha.js
test/functional/crossFunctional.mocha.js
test/functional/druidFunctional.mocha.js
test/info.js

Druid 0.9.x

---

CHANGELOG.md
extra/pegjs.js
src/actions/splitAction.ts
src/expressions/expression.pegjs
src/expressions/plyql.pegjs
test/parser/expressionParser.mocha.js
test/parser/plyqlParser.mocha.js

- Added convenient filtered aggregators to PlyQL like: `SUM(added WHERE cityName = 'San Francisco')`
- Fixed PlyQL incorrectly parsing `SELECT COUNT(page)`

Parser rewrite

---

docs/index.md
docs/plyql.md

updated plywood docs, moved plyql examples to here

---

CHANGELOG.md
data/mysql/load-data
script/docker-start
src/datatypes/dataset.ts
src/datatypes/external.ts
src/expressions/baseExpression.ts
src/expressions/plyql.pegjs
src/external/druidExternal.ts
test/functional/crossFunctional.mocha.js
test/functional/druidFunctional.mocha.js
test/overall/computeBig.mocha.js
test/parser/plyqlParser.mocha.js
test/simulate/amplabBenchmarkSQL.mocha.js
test/simulate/simulateDruid.mocha.js

- Fixed DruidExternal sometimes generating an invalid Druid query when doind a multi-dimensional split that includes time
- Unsuppress datasource when it is limited or selected
- Better show query support

better show query

---

CHANGELOG.md
src/actions/inAction.ts
src/datatypes/common.ts
src/datatypes/range.ts
src/datatypes/set.ts
src/dialect/sqlDialect.ts
src/expressions/literalExpression.ts
src/external/druidExternal.ts
test/functional/crossFunctional.mocha.js

Made filters on non primary time dimensions work in DruidExternal
Added basic tests for legacy Druid versions

alt time filters work

---

CHANGELOG.md
src/datatypes/dataset.ts
src/external/druidExternal.ts
test/datatypes/dataset.mocha.js
test/functional/crossFunctional.mocha.js
test/functional/druidFunctional.mocha.js
test/functional/mySqlFunctional.mocha.js
test/functional/postgresFunctional.mocha.js

- Druid: Default to JavaScript filter for negative bounds in bound filter
- Add tests around negative numbers

Improve negative values

---

CHANGELOG.md
src/datatypes/range.ts
src/expressions/literalExpression.ts
src/external/druidExternal.ts
test/functional/crossFunctional.mocha.js
test/simulate/simulateDruid.mocha.js

Druid Fixed number range behaviour in nested splits

Fix number range

---

.idea/dictionaries/vadim.xml
CHANGELOG.md
compile-tsc
src/actions/joinAction.ts
src/datatypes/external.ts
src/external/druidExternal.ts
src/helper/promiseWhile.ts
test/external/druidExternal.mocha.js
test/external/druidExternalIntrospection.mocha.js
test/functional/crossFunctional.mocha.js
test/functional/druidFunctional.mocha.js
test/helper/promiseWhile.mocha.js
test/simulate/amplabBenchmarkSQL.mocha.js
test/simulate/simulateDruid.mocha.js
typings/q/Q.d.ts

- Druid Select query no longer bound to 10000 max limit and will use itterative strategy
- Numeric Dimensions can be aggregated

Complex query

---

CHANGELOG.md
src/datatypes/range.ts
test/overall/compute.mocha.js

- Added compare to ranges so they sort correctly

fixed range compare

---

.idea/dictionaries/vadim.xml
CHANGELOG.md
docs/expressions.md
src/datatypes/dataset.ts
test/overall/compute.mocha.js

native quantiles work

---

CHANGELOG.md
package.json
src/datatypes/attributeInfo.ts
src/datatypes/external.ts
src/external/druidExternal.ts
test/external/druidExternal.0.9.0.mocha.js
test/external/druidExternal.0.9.1.mocha.js
test/external/druidExternal.mocha.js
test/external/external.mocha.js
test/functional/crossFunctional.mocha.js
test/info.js
test/mocha.opts
test/simulate/simulateDruid.0.8.3.mocha.js
test/simulate/simulateDruid.0.9.0.mocha.js
test/simulate/simulateDruid.0.9.1-legacy-lookups.mocha.js
test/simulate/simulateDruid.0.9.1.mocha.js
test/simulate/simulateDruid.mocha.js
test/simulate/simulateMySQL.mocha.js

Takes advantage of most features in Druid 0.9.1

Druid0.9.1

---

CHANGELOG.md
src/expressions/baseExpression.ts
test/external/druidExternal.0.9.0.mocha.js
test/external/druidExternal.mocha.js
test/external/druidExternalLegacy.mocha.js
test/simulate/simulateDruid.0.8.3.mocha.js
test/simulate/simulateDruid.0.9.0.mocha.js
test/simulate/simulateDruid.mocha.js

no JS globals

---

CHANGELOG.md
src/external/baseExternal.ts
src/external/druidExternal.ts
test/external/druidExternal.mocha.js
test/external/external.mocha.js
test/functional/crossFunctional.mocha.js
test/functional/druidFunctional.mocha.js
test/simulate/simulateDruid.mocha.js

- Renamed `customExtractionFns` to `customTransforms`
- Using lowercase `alphanumeric` in `dimensionOrder`

renamed to transforms

---

src/datatypes/attributeInfo.ts

set special no matter what, check unsplitable is equal, add change fn

Add change to attribute info

---

src/expressions/plyql.pegjs
src/expressions/refExpression.ts
test/expression/expression.mocha.js
test/parser/plyqlParser.mocha.js

null check for object.keys
to string cleanup
implemented getfn

Case insensitive continued

---

src/external/baseExternal.ts
test/external/external.mocha.js

select order

---

src/datatypes/dataset.ts
src/datatypes/range.ts
src/datatypes/set.ts
src/datatypes/timeRange.ts
test/datatypes/dataset.mocha.js
test/datatypes/set.mocha.js
test/datatypes/timeRange.mocha.js
test/external/external.mocha.js

-timezone to tabular and table displays
-add ordered columns option to flatten options

Timezone, ordering

---

src/expressions/plyql.pegjs
test/parser/plyqlParser.mocha.js

also properly comment out links in parser

show warnings, index

---

CHANGELOG.md
src/external/druidExternal.ts

backport #215

---

package-lock.json
package.json

Updated `druid-query-toolkit` to the latest version

Updated druid-query-toolkit

---

.gitignore
CHANGELOG.md
package.json

Updated CHANGELOG, version in package.json, and ignored runConfigurations

Version bump

---

package-lock.json
package.json
src/external/utils/druidFilterBuilder.ts
test/simulate/simulateDruid.mocha.js

mvOverlap translates to a native query using an IN filter
mvContains translates to a native query using an AND filter with SELECTOR filters for each field

Mv overlap mv contains native filter

---

package-lock.json
package.json
test/expression/inExpression.mocha.js

I need to downgrade because I forgot `np` does the file change while pushing to npm.

Downgrade to 0.29.1 and run prettier

---

extra/prefix.js
package-lock.json
package.json
src/expressions/sqlAggregateExpression.ts
src/expressions/sqlRefExpression.ts
src/external/druidSqlExternal.ts
src/helper/containsSqlFunction.ts
test/expression/sqlAggregateExpression.mocha.js

This reverts commit de83eb70c52ecd4986da5a175fece21e399bcc2b.
We're not ready to move to the new package yet.

Revert "@druid-toolkit/query@0.1.4 (#286)"

---

test/datatypes/dataset.mocha.js

Updates the the dataset tests to reflect the [changes to the TSV and CSV finalizers](https://github.com/implydata/plywood/pull/294).

Update dataset test

---

extra/prefix.js

We are also using __assign, __awaiter, and __generator

Add missing tslib imports to prefix

---

.idea/prettier.xml
.idea/watcherTasks.xml
src/expressions/notExpression.ts
test/functional/druidSqlFunctional.mocha.js
test/functional/mySqlFunctional.mocha.js
test/info.js
test/simulate/simulateDruidSql.mocha.js

Use the 2-value IS NOT TRUE instead of 3-value NOT which is more in-keeping with the original intention of Plywood (adapting to Druid getting 3-value logic on by default)

use 2-value IS NOT TRUE instead of 3-value NOT

---

src/datatypes/set.ts
test/datatypes/set.mocha.js

Removing a value in a Set should update the setType accordingly

Update set type when removing a value

---

src/external/utils/druidFilterBuilder.ts
test/simulate/simulateDruid.mocha.js

... turns out it could actually get there!

fix double filter that results in false
