implydata/plywood

.idea/dictionaries/vadim.xml, .idea/inspectionProfiles/Project_Default.xml, CHANGELOG.md, package.json, src/actions/applyAction.ts, src/actions/baseAction.ts, src/actions/inAction.ts, src/actions/splitAction.ts, src/datatypes/common.ts, src/datatypes/dataset.ts, src/datatypes/external.ts, src/dialect/sqlDialect.ts, src/expressions/baseExpression.ts, src/expressions/chainExpression.ts, src/expressions/externalExpression.ts, src/expressions/literalExpression.ts, src/expressions/refExpression.ts, src/expressions/sql.pegjs, src/external/druidExternal.ts, src/external/mySqlExternal.ts, test/actions/actions.mocha.coffee, test/overall/composition.mocha.coffee, test/overall/compute.mocha.coffee, test/overall/sqlParser.mocha.coffee, test/simulate/simulateDruid.mocha.coffee, test/simulate/simulateMySQL.mocha.coffee
Many things here:
- Paving the road for multi-dimensional splits `.split({ Page: '$page', User: '$user' })`
- Fixed problems with SELECT queries
- Allow for SQL parsing of `SELECT *`
- Fix support for `sort` and `limit` in SELECT queries
- Better escaping in MySQL driver
=> Multi-dimensional split groundwork

src/expressions/baseExpression.ts
this keeps webstorm, etc, from complaining if contains is used without 2 arguments, since the compare value is optional on the ContainsAction
=> fix contains signature so compare is optional

docs/index.md
For `.apply('Pages', ...)`, the output should include a `Pages` property
=> Fix typo in output example

.idea/dictionaries/vadim.xml, CHANGELOG.md, compile-tsc, data/druid/Dockerfile, src/actions/baseAction.ts, src/actions/substrAction.ts, src/actions/timeBucketAction.ts, src/actions/timeFloorAction.ts, src/actions/timePartAction.ts, src/actions/timeRangeAction.ts, src/actions/timeShiftAction.ts, src/datatypes/timeRange.ts, src/expressions/baseExpression.ts, src/expressions/literalExpression.ts, src/expressions/plyql.pegjs, src/external/druidExternal.ts, src/helper/dates.ts, src/init.ts, test/external/druidExternal.mocha.js, test/external/druidExternalLegacy.mocha.js, test/functional/crossFunctional.mocha.js, test/helper/dates.mocha.js, test/info.js, test/overall/compute.mocha.js, test/overall/defineEnvironment.mocha.js, test/overall/stringification.mocha.js, test/overall/typecheck.mocha.js, test/parser/plyqlParser.mocha.js, test/simulate/simulateDruid.mocha.js
- Added ability to define the timezone through the environment
- Timezone always defaults to UTC
- Date parsing no longer done by PlyQL parser
- Added tests for legacy Druid versions
=> timezones, date literals, and legacy tests

.idea/inspectionProfiles/Project_Default.xml, CHANGELOG.md, package.json, src/expressions/baseExpression.ts, src/expressions/literalExpression.ts, src/expressions/plyql.pegjs, test/overall/composition.mocha.js, test/parser/plyqlParser.mocha.js
- Added SET expressions to PlyQL `{'A', 'B', 'C'}`
- PlyQL can now parse IN with arbitrary expression on right hand side
=> better set support in PlyQL

.idea/dictionaries/vadim.xml, CHANGELOG.md, docs/expressions.md, docs/plyql.md, src/actions/timePartAction.ts, src/dialect/sqlDialect.ts, src/expressions/baseExpression.ts, src/expressions/plyql.pegjs, src/external/druidExternal.ts, src/external/mySqlExternal.ts, test/external/druidExternal.mocha.js, test/functional/crossFunctional.mocha.js, test/parser/plyqlParser.mocha.js
- Dramatically reduced PlyQL parser size
- Added `YEAR` as a possible `timePart` value
- Added `CURDATE`, `PI`, `YEAR`, `MONTH`, `WEEK_OF_YEAR`, `DAY_OF_YEAR`, `DAY_OF_MONTH`,
`DAY_OF_WEEK`, `HOUR`, `MINUTE`, `SECOND`, `DATE`, `CURRENT_TIMESTAMP`, `LOCALTIME`,
`LOCALTIMESTAMP`, `UTC_TIMESTAMP`, `SYSDATE`, `CURRENT_DATE`, `UTC_DATE`, `DAY_OF_YEAR`,
`DOY`, `DOW`, `DAYOFMONTH`, `DAY`, `WEEKOFYEAR`, and `WEEK` to PlyQL
- Fixed bug where `DAY_OF_YEAR`, `DAY_OF_MONTH`, and `DAY_OF_WEEK` was zero indexed
=> Better plyql parser

.idea/dictionaries/vadim.xml, .idea/inspectionProfiles/Project_Default.xml, CHANGELOG.md, src/datatypes/dataset.ts, src/dialect/sqlDialect.ts, src/expressions/baseExpression.ts, src/expressions/chainExpression.ts, src/expressions/plyql.pegjs, src/external/druidExternal.ts, test/external/druidExternalIntrospection.mocha.js, test/overall/compute.mocha.js, test/parser/plyqlParser.mocha.js, test/simulate/amplabBenchmarkSQL.mocha.js, test/simulate/simulateMySQL.mocha.js
- Fix Druid introspection bug on JS ingestion aggregators
- Allow data-less PlyQL queries like `SELECT 1+1`
- Default PlyQL `AS` text now matches SQL implementation.
=> Fix Druid introspection bug on JS ingestion aggregators

CHANGELOG.md, data/druid/load-data, data/druid/wikipedia-compact-index.json, src/actions/baseAction.ts, src/actions/selectAction.ts, src/actions/timeFloorAction.ts, src/datatypes/common.ts, src/datatypes/external.ts, src/datatypes/timeRange.ts, src/expressions/baseExpression.ts, src/expressions/externalExpression.ts, src/expressions/literalExpression.ts, src/external/druidExternal.ts, test/actions/timeFloorAction.mocha.js, test/external/druidExternal.mocha.js, test/external/external.mocha.js, test/functional/druidFunctional.mocha.js, test/overall/referenceCheck.mocha.js, test/simulate/simulateDruid.mocha.js
- Ability to define delegates in Externals
- selectAction now type checks and only allows defined attributes to be selected
- `DruidExternal.getSourceList` now returns the sources in a sorted order
=> Add delegates

CHANGELOG.md, src/expressions/refExpression.ts, src/external/druidExternal.ts, test/external/druidExternal.mocha.js, test/functional/crossFunctional.mocha.js, test/simulate/amplabBenchmarkSQL.mocha.js, test/simulate/simulateDruid.mocha.js
- DruidExternal: Fix bug where `$blah / 10` did not work in split
- DruidExternal: Fix bug where `1 + $blah` did not cast to number
=> fixes for numeric expressions

.idea/misc.xml, CHANGELOG.md, docs/index.md, extra/postfix-lite.js, rrollup, src/datatypes/attributeInfo.ts, src/datatypes/dataset.ts, src/expressions/applyExpression.ts, src/expressions/averageExpression.ts, src/expressions/collectExpression.ts, src/expressions/countDistinctExpression.ts, src/expressions/filterExpression.ts, src/expressions/maxExpression.ts, src/expressions/minExpression.ts, src/expressions/quantileExpression.ts, src/expressions/sortExpression.ts, src/expressions/splitExpression.ts, src/expressions/sumExpression.ts, src/external/baseExternal.ts
- All Dataset computation and aggregation functions now take expressions instead of functions.
Each has a corresponding function that takes a function like the old API.
So `Dataset#apply(name, x)` now expects `x` to be and expression but `Dataset#applyFn(name, x)` has the old API
- `AttributeInfo#type` defaults to `STRING`
- Removed PlyQL parser from plywood-lite
=> better API for dataset functions

src/external/baseExternal.ts, test/external/external.mocha.js
Do we need that `typeof v === 'undefined'` check in every inflater?
=> Added null inflater

.idea/codeStyles/Project.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/jsLinters/eslint.xml, src/external/utils/druidExtractionFnBuilder.ts
**Purpose**
To fix uninformative error being returned when a expression is improperly constructed.
**Key Changes**
Plywood will now throw a single informative error when an expression is incorrect. Also, updated WebStorm settings to automatically run ESLint on save.
=> Added general error for an expression used in the wrong context

package.json
Updated druid-query-toolkit version from "0.13.2" to "0.14.10"
=> update druid-query-toolkit version

extra/prefix.js
Upgrading TypeScript necessitated a tslib upgrade and now they use ES exports.
=> Fix tslib prefix

package-lock.json, package.json
Targets the latest versions of immutable-class and chronoshift. No functional changes since Plywood does not use BaseImmutable and is therefore not affected by `useDefineForClassFields`.
=> Bump immutable-class and chronoshift

extra/prefix.js, rrollup, src/dialect/baseDialect.ts, src/dialect/druidDialect.ts, src/expressions/baseExpression.ts, src/expressions/mvFilterOnlyExpression.ts, test/simulate/simulateDruidSql.mocha.js
Adds `mvFilterOnly` expression, which is only supported in druidsql. Purposely undocumented because it is only added to support Pivot features.
=> Add support for MV_FILTER_ONLY in druidsql

rrollup, src/dialect/baseDialect.ts, src/dialect/druidDialect.ts, src/expressions/baseExpression.ts, src/expressions/index.ts, src/expressions/ipMatchExpression.ts, src/expressions/ipSearchExpression.ts, src/expressions/ipStringifyExpression.ts, src/external/utils/druidExpressionBuilder.ts, src/external/utils/druidFilterBuilder.ts, test/expression/expression.mocha.js, test/simulate/simulateDruid.mocha.js, test/simulate/simulateDruidSql.mocha.js
- Added two new expressions, `ipSearchExpression` and `ipMatchExpression`, into plywood to support `ip_search` and `ip_match` functions on ip/ip prefix columns. 
- Need to support both native query and druidSQL.
=> [IMPLY-23543] Added IpSearchExpression and IpMatchExpression to support ip_search and ip_match functions in both native query and druidSql

src/expressions/inExpression.ts, test/expression/inExpression.mocha.js, test/simulate/simulateDruidSql.mocha.js
This will allow conversion from a plywood inExpression (`$columnName.in(valuesArray)`) to SQL. 
Examples:
- `$first_name.in(['Onfroi'])` -> `(t."first_name"='Onfroi')`
- `$first_name.in(['Onfroi', 'Derby'])` -> `(t."first_name"='Onfroi' OR t."first_name"='Derby')`
- `$first_name.in(['Onfroi', 'Derby', 'Brier'])` -> `(t."first_name"='Onfroi' OR t."first_name"='Derby' OR t."first_name"='Brier')`
Note: The added tests are testing `simulateQueryPlan` which does not utilize `inExpression._getSQLChainableUnaryHelper` but I left them there because I wrote them and they seemed like useful tests.
=> Added ability to convert inExpression to SQL

src/datatypes/set.ts, test/datatypes/set.mocha.js, test/simulate/simulateDruidSql.mocha.js
This PR fixes the Plywood Set constructor function so that:
1. Plywoods generates the correct SQL query when both null and "null" are in a set. 
_Before_
`$('tags').overlap(['A', 'B', null, 'null'])` translates to `'tags' IN ['A', 'B', NULL, 'null']`,
_After_
`$('tags').overlap(['A', 'B', null, 'null'])` translates to `'tags' IS NULL OR 'tags' IN ['A', 'B', 'null']`,
2. Set can dedupe duplicate falsy values.
=> Fix Plywood Set constructor function does not handle null/"null" and falsy values properly

src/expressions/expression.pegjs, src/expressions/sqlRefExpression.ts, test/expression/sqlRefExpression.mocha.js, test/parser/expressionParser.mocha.js
This is a follow-up PR for #271 to make sure `Expression.parse` can parse string defined SqlRefExpressions (ex. `s${t.column}:IP`)
=> Added ability to express type for SqlRefExpression in plywood's expression language

.idea/prettier.xml, package-lock.json, package.json, rrollup, src/expressions/splitExpression.ts, src/helper/containsSqlFunction.ts, test/expression/splitExpression.mocha.js, test/helper/containsSqlFunction.mocha.js
If a SqlRefExpression.sql was `IP_SEARCH('192', IP_PREFIX_PARSE(IP_STRINGIFY("t"."net_dst")))` then SplitExpression.getSelectSql would incorrectly wrap this value with IP_STRINGIFY. And apparently I forgot to push the version update changes for `0.30.2` so those are in here.
=> Fix bug when generating select sql when IP_MATCH or IP_SEARCH is included

src/expressions/mvContainsExpression.ts, src/expressions/mvOverlapExpression.ts, test/expression/mvContainsExpression.mocha.js, test/expression/mvOverlapExpression.mocha.js
Jira Task: [IMPLY-29907](https://implydata.atlassian.net/browse/IMPLY-29907)
Context:
The error described in the ticket occurs because clicking on the color legend triggers `FilterClause.matches()` , which calls Expression.calc() inside. (https://github.com/implydata/imply-ui/blob/master/packages/pivot-common/src/models/filter-clause/filter-clause.ts#L469). For `MvOverlapExpression` and `MvContainsExpression` in Plywood, this function is not implemented.
[IMPLY-29907]: https://implydata.atlassian.net/browse/IMPLY-29907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added _calcChainableHelper for mvOverlapExpression and mvContainsExpression

src/datatypes/set.ts
Set.unifyElements elements should check that the accumulator is not null before adding it to new values. This will filter out null values and it will no longer throw an error. 
before: 
after:
=> add a null check to the accumulator in set.ts [IMPLY-32068]

src/datatypes/dataset.ts
We want null columns to be represented by a space and empty strings to be represented by "". To support this we need to add in special logic in both the TSV and CSV finalizers to return the right values.
=> add special cases for csv and tsv formatting [IMPLY-34859]

src/datatypes/range.ts, src/datatypes/timeRange.ts, src/expressions/baseExpression.ts, src/expressions/timeBucketExpression.ts, src/expressions/timeRangeExpression.ts, test/datatypes/timeRange.mocha.js, test/expression/expression.mocha.js, test/expression/timeBucketExpression.mocha.js, test/expression/timeRangeExpression.mocha.js
We use TimeRange and TimeBucket Expression to create the presets in pivot, we need to be able to specify bounds on these types of expressions so when they get converted to just a TimeRange they don't always have the default bounds. If no bounds are passed in everything should behave as it previously did.
=> Accept time bounds for TimeRangeExpressions and TimeBucketExpressions

src/dialect/druidDialect.ts, test/simulate/simulateDruidSql.mocha.js
Reverts implydata/plywood#301
We are going to revisit this approach at a later date.
=> Revert "fix how cast to boolean works to preserve null"

src/helper/utils.ts, test/simulate/simulateDruidSql.mocha.js
A refinement for the `.overlap([null])` case in https://github.com/implydata/plywood/pull/306
=> allow overlap with [null]

src/expressions/refExpression.ts, src/external/druidExternal.ts, src/external/druidSqlExternal.ts, src/types.ts
This PR makes the necessary changes to support the TIME_SERIES type.
=> Support time series in PlyType
